### ISSUE TITLE
Suggestion on template repository and nightly

### ISSUE THREAD

**Issue by yuchanns** [glepnir/cosynvim#1]
Hey! glad to see your re-activity after a period down(as just my speculation). And `fernvim` is really nice.

I would suggest you to make this repo as a template repository so that ppl can generate theirs with the same structure. See [Creating a template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository).

In addition, the nightly config on `lua/core/options.lua` will cause error on none nightly version (mine is 0.7.2). May you consider add a version detection with `vim.inspect(vim.version())` or such thing?

**Comment by glepnir** [comment]
now should work in 0.7 and is tempalte now
