### ISSUE TITLE
能否在 windows 10 下安装？

### ISSUE THREAD

**Issue by lilx2018** [glepnir/cosynvim#20]
我在 windows 下安装，启动后显示空白界面，SPC f f 提示 E492: 不是编辑器的命令: Telescope find_files，这其中有什么机关？

具体操作如下：
1. cd ...\AppData\Local\,  git clone https://github.com/glepnir/cosynvim nvim
2. 启动 neovim，自动 clone packer.vim，成功。
3. 进入 PackerSync 界面，提示成功。
4. 关闭 neovim，再次启动 neovim，neovim 显示一个空白界面（指的是空的 buffer，而不是欢迎或dashboard界面），why?
5. SPC f f 提示 E492: 不是编辑器的命令: Telescope find_files（检查 nvim-data 下的 site\pack\packer\start 目录，没有任何文件，似是没有安装任何插件，why?）

**Comment by glepnir** [comment]
这只是个template。 不是个特别完整的配置。 你自己要改改路径吧。 我好像没适配windows的path separate。能成功很意外。。
没有的话你执行下 `PackerCompile` 重新编译一下试试

**Comment by lilx2018** [comment]
似乎改一个地方就可以了，多谢。

function Packer:load_plugins()
  self.repos = {}

  local get_plugins_list = function()
    local list = {}
    local tmp = vim.split(fn.globpath(modules_dir, '*/plugins.lua'), '\n')
    for _, f in ipairs(tmp) do
      -- Windows 下路径连接符是 \\
	  -- list[#list + 1] = string.match(f, 'lua/(.+).lua$')
	  list[#list + 1] = string.match(f, 'lua\\(.+).lua$')
    end
    return list
  end

  local plugins_file = get_plugins_list()
  for _, m in ipairs(plugins_file) do
    require(m)
  end
end

**Comment by glepnir** [comment]
不止 。 你贴这个我都看到两个了。tmp那一行
