### ISSUE TITLE
关于telescope lazyload的一些问题

### ISSUE THREAD

**Issue by tinywaferShark** [glepnir/cosynvim#21]
在开始后会有很多插件没有load,之后我想使用telescope的话，第一次启动会出现很多红色的错误，在这之后就不会有问题请问有办法可以解决这个第一次使用未加载插件的错误嘛。下面这张图应该是cmp插件没有加载，导致使用会报错。有时候也会因为`telescope-fzy-native.nvim`这个插件没加载而报错

![2022-09-14_14-46](https://user-images.githubusercontent.com/97378664/190080849-a5342027-a4a6-4cd5-8ed0-f3b553a2f7b9.png)

![2022-09-14_14-47](https://user-images.githubusercontent.com/97378664/190081331-5902c948-02cf-453a-99ba-a0925e012634.png)

**Comment by glepnir** [comment]
需要load的依赖在启用的时候判断一下手动load就行了

**Comment by glepnir** [comment]
或者禁用cmp在telescope prompt buffer。

**Comment by tinywaferShark** [comment]
> 需要load的依赖在启用的时候判断一下手动load就行了

像这种插件 应该怎么手动启动呢。我不知道这部分内容应该在哪里找到，我尝试去  [packer](https://github.com/wbthomason/packer.nvim)里找manualy load的内容，但不知道怎么手动启动这种插件
![图片](https://user-images.githubusercontent.com/97378664/190297807-e829141e-1056-4b6f-89d5-8950b8cbcbb6.png)

**Comment by glepnir** [comment]
telescope相关的我都手动加载了已经，我代码里有你那个错误是没有加载cmp，和telescope没啥关系

**Comment by tinywaferShark** [comment]
如果我进入一个启动了cmp的文件，我这里是一个c的文件，然后我在 使用telescope的话，他就会提示fzy-native的问题。我不知道怎么解决这个问题。
![图片](https://user-images.githubusercontent.com/97378664/190302516-ccf0b8b5-bdbc-4890-806f-c77b01b3223d.png)
![图片](https://user-images.githubusercontent.com/97378664/190302579-7e5ff368-dddb-470b-92ec-794d607a4cb8.png)

**Comment by glepnir** [comment]
没有这个文件. 查看你packercompiled文件，你那个目录应该有多个

**Comment by tinywaferShark** [comment]
![图片](https://user-images.githubusercontent.com/97378664/190346741-aee2e2ac-f405-4542-8ab2-0a3443c6fdc8.png)
是这个文件夹下的COMPILED文件嘛，本来有一个bak_compiled.lua被我删了，删除完也会出现这个问题，我清空了所有nvim缓存重新下载也会有这个问题。
那我还是直接用whichkey那种快捷键吧

**Comment by glepnir** [comment]
你吧这个也删了。重新compile
