### ISSUE TITLE
tansparent line at right side

### ISSUE THREAD

**Issue by notwidow** [glepnir/cosynvim#24]
How to get rid of that transparent line at right side of file. The line starts from top to bottom....
Help needed....

**Comment by notwidow** [comment]
okay transparency option found... looking for that line option to disable it.

**Comment by glepnir** [comment]
which transparent line ?

**Comment by notwidow** [comment]
![177981299-0e935c5f-545a-4e9c-a3ce-431e3c079b76](https://user-images.githubusercontent.com/112823418/191907363-5baeeec7-977e-4de0-ac6b-01313a88fc33.png)
Here .I'm not on laptop currently so here I downloaded this from your personal nvim files on GitHub.. look at the right side.. that transparent line

**Comment by notwidow** [comment]
> which transparent line ?

**Comment by glepnir** [comment]
you mean this ?

![image](https://user-images.githubusercontent.com/41671631/191907976-9e55faf8-d1ee-4491-8500-992ddf3023f3.png)

**Comment by notwidow** [comment]
> you mean this ?
> 
> ![image](https://user-images.githubusercontent.com/41671631/191907976-9e55faf8-d1ee-4491-8500-992ddf3023f3.png)

Yes

**Comment by glepnir** [comment]
`:h colorcolumn`

**Comment by notwidow** [comment]
> `:h colorcolumn`

What.....I searched for :h colorcolum last night.... But I did not read it bcuz I was sleepy... Thanks for confirming

**Comment by notwidow** [comment]
> `:h colorcolumn`

BTW can I know why you enabled it ?

**Comment by glepnir** [comment]
you need read some unix coding style book.  Displays in the past were so small that they could only display 80 widths. 
So in order to show some hints. Set both the colorcolumn and textwidth options to 80

**Comment by notwidow** [comment]
> you need read some unix coding style book. Displays in the past were so small that they could only display 80 widths. So in order to show some hints. Set both the colorcolumn and textwidth options to 80

Thanks

**Comment by notwidow** [comment]
I live in a country where technology is not advanced and none are interested in tech... I also visited all the well known book shops in my city to find Unix books or any internet related tech books and found none... My bad luck... I then asked from my friends and they told me no one cares about tech here and I will have to outside for these things... So yes I need to read Unix coding books and other it books as well.. haha I alone do research on internet and all on my own...the biggest problem for me is the internet access... Very hard to get internet access here .. even more harder than that is having a good download speed.. I get 50-700kbps download speeds and you can imagine how I feel about it? Maybe you can't if you never faced such a situation... Hahahaha ..
