### ISSUE TITLE
Error in completion

### ISSUE THREAD

**Issue by notwidow** [glepnir/cosynvim#25]
Hi,  i get this error when enter insert mode.
![IMG20221011090650](https://user-images.githubusercontent.com/112823418/194995039-7ea75773-c220-4c73-a5c9-89e0360df6f5.jpg)

** INFO **
> Cosynvim
nvim v0.8.0
OS: Artix Linux rolling
DE: KDE Plasma 5.25.5
Terminal: Alacritty

**Comment by glepnir** [comment]
that mean does not find nvim-cmp plugin.

**Comment by notwidow** [comment]
> that mean does not find nvim-cmp plugin.

then?

**Comment by glepnir** [comment]
make sure installed the nvim-cmp and loaded in runtimepath.

**Comment by notwidow** [comment]
> make sure installed the nvim-cmp and loaded in runtimepath.

nvim-cmp is installed

**Comment by glepnir** [comment]
so does it loaded when you trigger luasnip.

**Comment by notwidow** [comment]
> so does it loaded when you trigger luasnip.

when i try to go in insert mode that error comes the first time .. and this is the result
![Uploading IMG20221011124010.jpg…]()

**Comment by glepnir** [comment]
that mean not loaded if you make sure it installed.

**Comment by notwidow** [comment]
> that mean not loaded if you make sure it installed.

it is in installed plugins but its not loaded in files

**Comment by notwidow** [comment]
> that mean not loaded if you make sure it installed.

i personally dont like snippets and i dont care about them but for lagnuages like html.. i need them my main goal is to get snippets for html and others tag like languages and no more. Also i dont use lsp ... i want without lsp

**Comment by glepnir** [comment]
I had update some codes in cosy .please update then test.

**Comment by notwidow** [comment]
> I had update some codes in cosy .please update then test.

i dont know how to update cosynvim but i will remove everything from my pack.lua and will paste the updated one

**Comment by glepnir** [comment]
this is a template plugin :) if you don't need lsp .you  need  remove some lsp relate plugins.

**Comment by notwidow** [comment]
> this is a template plugin :) if you don't need lsp .you need some lsp relate plugins.

okay. first thing.... 
when i open any file in core folder than it loads fine without errors but the startup time is now slow. 
and when i open neovim outside core folder than it says helper not found and neovim is default one without plugins. I copy pasted your pack ,options file and created helper with added your content. Updated plugins.lua and config.lua according to your commits.

**Comment by glepnir** [comment]
a typo here . `you need remove lsp plugins in cosynvim`.

please do `PackerCompile` recompile. i had changed the nvim-cmp and lusnip load event.

**Comment by notwidow** [comment]
> a typo here . `you need remove lsp plugins in cosynvim`.
> 
> please do `PackerCompile` recompile. i had changed the nvim-cmp and lusnip load event.

i did packercompile.. and now PackerSync tries to remove all plugins folders

**Comment by glepnir** [comment]
now use XDG based dir. if you config it ,it will be used .

**Comment by notwidow** [comment]
> now use XDG based dir. if you config it ,it will be used .

okay i removed my nvim config and cloned your cosynvim just now and this is what i got while opening neovim.
![Screenshot_20221011_144837](https://user-images.githubusercontent.com/112823418/195058290-4559b671-4e45-4b8f-9500-af7d81010a4d.png)

**Comment by glepnir** [comment]
sry a function name is wrong. fixed.

**Comment by notwidow** [comment]
> sry a function name is wrong. fixed.

so is it fixed now?

**Comment by glepnir** [comment]
right

**Comment by notwidow** [comment]
> right

okay i cloned the repo again and this occured 
![Screenshot_20221011_152040](https://user-images.githubusercontent.com/112823418/195065389-bfe1c6f1-6bf4-42ca-b3a0-4ba40a78c00c.png)

**Comment by glepnir** [comment]
fixed.
