### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by notwidow** [glepnir/cosynvim#26]
Hi, How to set Tab key for selection of next item in snippet ? and the suggestions that come is annoying the that if i write function and hit enter then it prints the body of snippet. So how to configure it to not select snippet by default and only when i press tab to choose snippet?
THANKS!!!

**Comment by EpsilonKu** [comment]
Remove from cmp config `    preselect = cmp.PreselectMode.Item`

**Comment by notwidow** [comment]
> Remove from cmp config ` preselect = cmp.PreselectMode.Item`

that did nit worked. i commented it out but still upon pressing enter the first snippet is used
