### ISSUE TITLE
issues in setup

### ISSUE THREAD

**Issue by notwidow** [glepnir/cosynvim#27]
HI, whenever i open a file with ``` .db ``` extension this error pops up.
![Screenshot_20221020_123316](https://user-images.githubusercontent.com/112823418/197001353-f768dfb2-229e-454f-bfae-9f158afa2573.png)

2. no highlights in html files.
![Screenshot_20221020_154705](https://user-images.githubusercontent.com/112823418/197001570-68b52930-fe10-4261-b217-a84a5c68f854.png)

**Comment by glepnir** [comment]
neovim issue . i will fix in upstream.

**Comment by notwidow** [comment]
> neovim issue . i will fix in upstream.

hey glepnir, when will highlights in html gets fixed.

**Comment by glepnir** [comment]
html highlight works for me

**Comment by notwidow** [comment]
> html highlight works for me

but why not for me?..

**Comment by notwidow** [comment]
![IMG20221027142612](https://user-images.githubusercontent.com/112823418/198247500-d61be186-1ff9-48ef-9fd6-02ad35327f1d.jpg)
it works like this but not when applied
![IMG20221027142626](https://user-images.githubusercontent.com/112823418/198247591-7d1876c2-ca5a-430c-8a5a-d20a43e0fca1.jpg)

**Comment by glepnir** [comment]
you need check the treesitter load in this buffer or not.

**Comment by notwidow** [comment]
![IMG20221027143550](https://user-images.githubusercontent.com/112823418/198249334-6b5b4074-1663-4ef7-b43e-a1160f147dd3.jpg)
by the way .. do you use up to date plugins? becuase it was working for me also but one day upon editing html file it showed like this

**Comment by glepnir** [comment]
for me it works like this . this is worked. 

![image](https://user-images.githubusercontent.com/41671631/198250690-7789269b-06ae-4e6a-ac89-7a466369e747.png)

**Comment by notwidow** [comment]
![16668669168939220528601640526661](https://user-images.githubusercontent.com/112823418/198262705-831ba1fc-c96c-4303-a8d4-f737bdeabc0a.jpg)
changing the colorscheme fixed it. and i also remember there was a commit done to zephyr.. and after that this html highlights are gone... please have a look at it

**Comment by glepnir** [comment]
oh I will take a look at it later.

**Comment by notwidow** [comment]
> oh I will take a look at it later.

thanks.. btw 
> Arch Linux 
Nvim v0.8.0
kitty terminal
Gnome 42.5
