### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by notwidow** [glepnir/cosynvim#28]
HI, one small request is to make the dashboard feature of making newfile more advanced. 

For example....
If i want to create a new file from dashboard and i press enter on it. then before opening the empty file it should ask about the file name. like when selected then a small window popup should appear asking for the file name. In this way we wont be needed to save the file in order for syntax-highlighting and more.
Additionally
It would also be great if it becomes able to create directorys or subdirectorys for the file also. like if in the popup window when it asks for file ``` example/lua.lua ``` is given the it should check the exmaple directory in the current directory and if it does not exists then it can create the directory as well with new file (with specified name)..... THANKS~~~!!!

**Comment by notwidow** [comment]
i just noticed .. i opened dashboard issue in cosynvim.. sorry about that too...

**Comment by glepnir** [comment]
just copy content and open it in dashboard thanks.
