### ISSUE TITLE
`XDG_CONFIG_HOME` and `XDG_DATA_HOME` cannot be recongnize correcly by `core.helper`

### ISSUE THREAD

**Issue by yqwu905** [glepnir/cosynvim#31]
Neovim support specify data and config dir by setting env `XDG_CONFIG_HOME` and `XDG_DATA_HOME`, but cosynvim seem don't support that. I believe this's cause by `core.helper` only check for `XDG_CONFIG_DIR` and `XDG_DATA_DIR`.
Maybe you can use `vim.fn.stdpath('config')` and `vim.fn.stdpath('data')` instead of manully check env variables and find the config dir? This can ensure the consistency of behavior with neovim.

**Comment by glepnir** [comment]
this is work for my cli it's outside of neovim.
