### ISSUE TITLE
issues in python

### ISSUE THREAD

**Issue by notwidow** [glepnir/cosynvim#32]
Hi, i have 2 issues i face again and again in python.
1. Whenever i create a set in python then the indent applied is doubled. 
2. When i want to change a long line in python then that line is auto divided in 2 lines.
![IMG20221220070752](https://user-images.githubusercontent.com/112823418/208564447-44632eac-2379-46cc-9f91-cf4e08bbd02c.jpg)

The first one is confirmed issue with neovim.  and idk about the 2nd but it sometimes make it 2. 
Note: Im not talking about wrap. but sometimes the long line becomes 2 lines when i try to change it.

**Comment by glepnir** [comment]
`:h textwidth`

**Comment by notwidow** [comment]
> `:h textwidth`

and what about double indent ? the screenshot
