### ISSUE TITLE
想问一下为什么从 cosynvim 转变成 dope

### ISSUE THREAD

**Issue by Jerry-Moo** [glepnir/cosynvim#37]
我之前clone 了cosynvim 再慢慢学习如何用lua 配置nvim..今天上来发现你更新了整个项目。而且我发现core 的很多内容都改变了。helper.lua 和 options.lua  都有修改。想问一下是之前的配置有很大的不足吗?  同时想问一下我如果现在要配置一下lua nvim是按照depo 还是以前的cosynvim呢

**Comment by glepnir** [comment]
cli 之前一直没有从我配置移植过来。 options简化了一下有的大部分人用不上。 helper主要是给core和cli 提供个哦能。 dope 和cosy 没什么区别。 只不过加了cli 你可以在终端通过 /bin/dope 进行操作。 支持动态debug 显示插件信息等等。没什么差别。可以理解为更加完整
