### ISSUE TITLE
Question: How to enable search count

### ISSUE THREAD

**Issue by NoirJ0e** [glepnir/cosynvim#44]
By default, it appears that neovim will calculate the frequency of search results., e.g:
<img width="75" alt="image" src="https://user-images.githubusercontent.com/60462008/222957845-245da859-8458-434d-b40f-23bb6f273168.png">

However, while using this template, it appears that the function has been disabled. I attempted to modify `opt.shortmess` in `lua/core/option.lua`, but no changes were observed. Through it doesn't bother my daily usage, my curiosity about how to restore this function persists.

**Comment by glepnir** [comment]
the output of `set shortmess` ? if you want see the search results count. it should not include `S`

**Comment by NoirJ0e** [comment]
the result is : `shortmess=aoOTIcF`, same as default in this template

**Comment by glepnir** [comment]
did you config the `cmdheight`?  output of `set cmdheight?`

**Comment by NoirJ0e** [comment]
i didn't change anything in `lua/core/options.lua`, the value is 0

**Comment by NoirJ0e** [comment]
i see, i should adjust the `cmdheight` to make it work, thx 👍
