### ISSUE TITLE
E5113: Error while calling lua chunk: vim/loader.lua:0: attempt to call upvalue '' (a nil value)

### ISSUE THREAD

**Issue by ovidiu-eremia** [glepnir/cosynvim#53]
Hello,

First thank you for the concise structure for nvim configs.
Second, I need your help with this error I got after installing nvim from source on Ubuntu and cloning your `dope` in the `~/.config/nvim` and running it with `./bin/dope`
```
Error detected while processing /home/user/.config/nvim/init.lua: E5113: Error while calling lua chunk: vim/loader.lua:0: attempt to call upvalue '' (a nil value) local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:
```
Thank you,
Ovi

**Comment by glepnir** [comment]
emm what about just open nvim  and did you use any config before with lazy

**Comment by ovidiu-eremia** [comment]
> emm what about just open nvim

Thanks for answering!
That is what I get when trying to open nvim ^^^
I didn't use any config with lazy before and even deleted `~/.local/share/nvim/lazy` when I saw these issues...
Of course upon re-opening nvim lazy got automatically cloned back in the share folder.

**Comment by glepnir** [comment]
yup it has bootstrap if lazy don't find it will auto download. and what's your neovim version and check there has cache file in neovim cache dir  `~/.cache/nvim`.

**Comment by ovidiu-eremia** [comment]
> neovim version
![image](https://github.com/nvimdev/dope/assets/33250839/ae9855a7-3647-4e5e-b067-ef4cf9168f58)

> ~/.cache/nvim
![image](https://github.com/nvimdev/dope/assets/33250839/20c331dc-952a-467c-8bb6-107f075c7007)

**Comment by glepnir** [comment]
seems like before your config create some cache . `rm -rf ~/.cache/nvim` and retry it again.

**Comment by ovidiu-eremia** [comment]
> rm -rf ~/.cache/nvim
delete it

and when starting neovim I still get:
```
Error detected while processing /home/user/.config/nvim/init.lua: E5113: Error while calling lua chunk: vim/loader.lua:0: attempt to call upvalue '' (a nil value) local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:
```

**Comment by ovidiu-eremia** [comment]
Should I try re-installing nvim with [bob](https://github.com/MordechaiHadad/bob) ?

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/releases/tag/nightly could you try download this ?

**Comment by glepnir** [comment]
and cleanup your env remove `.local/share/nvim` and `cache/nvim`

**Comment by ovidiu-eremia** [comment]
Now neovim opened without an error, but when trying to open a file it shows:
```
You are trying to call the setup function of indent-blankline v
ersion 2, but you have version 3 installed
```

**Comment by ovidiu-eremia** [comment]
I tried to update with `dope` but I got this:
![image](https://github.com/nvimdev/dope/assets/33250839/541b74b0-ed61-433b-a222-88628b162d9c)

**Comment by glepnir** [comment]
check indent-blankline you install version 3 but config it use version2 ? idk. i don't use that plugin.
